[package]
name = "dis68k"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "68kdis"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
